# SECURITY WARNING: This file allows you to store sensitive keys.
# Do not commit this file to version control.

kis:
  app_key: "PSKathJKCFoaHDh6gVITH5gC3sRhmGILFZXa"
  app_secret: "mvn08ZOmNA6LzirPE8VrcK1UyQ95I15LkbnRtSF13BJEV9uP6+mJml4C9xCGkn3OM+4jFbuweJ2K8ypFcTRofWq3Rqo2oB/oyn2M4rvjd8cduSyDfaEOF7r/043/Jl8H8g2CCNegoqahJZfZ9WFMkhOJXhbQOrP2Np7BYMujOOd5enlUln4="
  account_no: "46865039"
  account_code: "01"
